# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 05:19
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
