# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='/static/no-avatar.jpg', upload_to='avatars', verbose_name='picture')),
                ('skype', models.CharField(default='example', max_length=40, verbose_name='skype')),
                ('phone_number', models.CharField(default='+380123456789', max_length=15, verbose_name='phone number')),
                ('facebook_profile', models.URLField(default='https://facebook.com/exemple', max_length=60, verbose_name='facebook profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
